# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.SlugField(max_length=126, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_name', models.CharField(max_length=100)),
            ],
        ),
    ]
