# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 22:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_survey', '0002_add_breed_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='birth_month',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='breed_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pet_survey.Breed'),
        ),
        migrations.AddField(
            model_name='pet',
            name='breed_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pet_survey.Breed'),
        ),
        migrations.AddField(
            model_name='pet',
            name='breed_count',
            field=models.IntegerField(choices=[(0, b'Breed not known'), (1, b'One primary breed'), (2, b'Two primary breeds')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='is_fixed',
            field=models.BooleanField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.PositiveIntegerField(),
            preserve_default=False,
        ),
    ]
